export const AUTH_OK = 'AUTH_OK';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SERIAL_OK = 'SERIAL_OK';
export const SERIAL_ERROR = 'SERIAL_ERROR';
export const SERIAL_CONFIRM_OK = 'SERIAL_CONFIRM_OK';
export const SERIAL_CONFIRM_ERROR = 'SERIAL_CONFIRM_ERROR';
export const MODEL_OK = 'MODEL_OK';
export const MODEL_ERROR = 'MODEL_ERROR';
// export const PART_OK = 'PART_OK';
export const PART_DUPLICATE_ERROR = 'PART_DUPLICATE_ERROR';
export const PART_INVALID_ERROR = 'PART_INVALID_ERROR';
export const PART_ERROR_SCRIPT = 'http://admin:passpower@127.0.0.1:8001/script?run001=run';
export const SERIAL_CONFIRM_OK_SCRIPT = 'http://admin:passpower@127.0.0.1:8001/script?run017=run ';
